# https://about.gitlab.com/2016/05/23/gitlab-container-registry/
stages:
  - build
  - test
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/perobertson/requisition/tests:$CI_BUILD_REF_NAME
  CONTAINER_TEST_IMAGE_LATEST: $CI_REGISTRY/perobertson/requisition/tests:master
  RAILS_ENV: test
  RACK_ENV: test
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: ""

build_image:
  stage: build
  image: docker:git
  tags:
    - docker
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE_LATEST || true
    - docker pull $CONTAINER_TEST_IMAGE || true
    - docker build --pull --cache-from="$CONTAINER_TEST_IMAGE_LATEST" --cache-from="$CONTAINER_TEST_IMAGE" -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

rubocop:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  tags:
    - docker
  script:
    - bundle exec rubocop --rails --fail-level=warning --display-cop-names --format=progress --format=offenses --format=html --out="rubocop.html"
  artifacts:
    paths:
      - rubocop.html

brakeman:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  tags:
    - docker
  script:
    - bundle exec brakeman --run-all-checks --rails5 --confidence-level=2

test_generated_files:
  stage: test
  image: ruby:2.5.5-alpine
  services:
  - postgres:9.6-alpine
  tags:
    - docker
  script:
    - apk update
    - apk add build-base git nodejs postgresql-dev tzdata
    - gem install bundler
    - bundle install
    - git status --short && test "$(git status --short | grep Gemfile.lock)" = ""
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - git status --short && test "$(git status --short | grep db/schema.rb)" = ""

rails_tests:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  services:
  - postgres:9.6-alpine
  tags:
    - docker
  artifacts:
    paths:
      - coverage/
  script:
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - bundle exec rails test

dependency_scanning:
  stage: test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  tags:
    - docker
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]

staging:
  stage: deploy
  image: ruby:2.5.5
  tags:
    - docker
  script:
    - ENVIRONMENT=staging ./bin/deploy
  environment:
    name: staging
  only:
    - master

production:
  stage: deploy
  image: ruby:2.5.5
  tags:
    - docker
  script:
    - ENVIRONMENT=production ./bin/deploy
  environment:
    name: production
  only:
    - master
  when: manual
