version: '3.7'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
    ports:
      - "3000:3000"

  db:
    image: postgres:9.6.16-alpine
